version: "3"

services:
  backend:
    build:
      backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VUE_APP_URL=http://localhost:5000
        - VUE_API_URL=http://localhost:5000/api
        - VUE_AUTH_URL=http://localhost:5000/oauth/token

    # environment:
      # - VUE_APP_URL=http://localhost:5000
      # - VUE_API_URL=http://localhost:5000/api
      # - VUE_AUTH_URL=http://localhost:5000/oauth/token
  
    ports:
      - 80:8080

