version: "3"

services:
  backend:
    build: backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: frontend-react
      dockerfile: Dockerfile
      args:
        - REACT_APP_URL=http://localhost:5000
        - REACT_APP_API_URL=http://localhost:5000
        - REACT_APP_AUTH_URL=http://localhost:5000
    ports:
      - "1000:80"
    volumes:
      - /app/node_modules

