version: "3"

services:
  backend:
    build: backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - REACR_APP_APP_URL=http://localhost:5000
        - REACR_APP_API_URL=http://localhost:5000/api
        - REACR_APP_AUTH_URL=http://localhost:5000/oauth/token
    ports:
      - "1000:8080"
    volumes:
      - .:/app
    command: npm start

